version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_HOST: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ${MOUNT}/servers/mariadb/db_init:/docker-entrypoint-initdb.d
      - ${MOUNT}/servers/mariadb/db:/var/lib/mysql
    cap_add:
      - SYS_NICE 
    restart: unless-stopped
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Calcutta
      PMA_ARBITRARY: 1
    volumes:
      - ${MOUNT}/servers/phpmyadmin/config:/config
    restart: unless-stopped
  mongo:
    container_name: mongo
    image: mongo
    hostname: ${MONGO_HOSTNAME}
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    restart: unless-stopped
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOSTNAME}:27017/
networks:
  default:
    name: proxy_default
    external: true